# Generated by Django 3.2.8 on 2022-01-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('login', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=1)),
                ('nip', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
