# Generated by Django 3.2.8 on 2022-02-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_alter_group_user'),
        ('user', '0004_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
