# Generated by Django 3.2.8 on 2022-01-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name_group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
