# Generated by Django 3.2.8 on 2022-02-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=3)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('mac', models.CharField(default='', max_length=100, null=True)),
                ('power_state', models.CharField(default='', max_length=50, null=True)),
                ('so', models.CharField(max_length=1)),
                ('description', models.TextField(null=True)),
                ('order', models.CharField(max_length=50)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machine', to='pool.pool')),
            ],
            options={
                'db_table': 'VIRTUAL_MACHINE',
            },
        ),
    ]
