# Generated by Django 3.2.8 on 2022-01-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pool', '0001_initial'),
        ('group', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_host', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('mac', models.CharField(default='', max_length=100, null=True)),
                ('so', models.CharField(max_length=1)),
                ('order', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='group.group')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='pool.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='user.user')),
            ],
            options={
                'db_table': 'HOST',
            },
        ),
    ]
