# Generated by Django 3.2.8 on 2022-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
