# Generated by Django 3.2.8 on 2022-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_alter_host_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='type_host',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
